import React, { useState } from 'react';
import { Student, Session, AttendanceRecord } from '../types';
import { getAttendanceInsights } from '../services/geminiService';
import { Sparkles, FileText, Loader2, AlertCircle } from 'lucide-react';
import ReactMarkdown from 'react-markdown';

interface GeminiInsightsProps {
    students: Student[];
    sessions: Session[];
    records: AttendanceRecord[];
}

const GeminiInsights: React.FC<GeminiInsightsProps> = ({ students, sessions, records }) => {
    const [report, setReport] = useState<string | null>(null);
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);

    const generateReport = async () => {
        setLoading(true);
        setError(null);
        try {
            const result = await getAttendanceInsights(students, sessions, records);
            setReport(result);
        } catch (err) {
            setError("Failed to generate report. Please try again later.");
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="max-w-4xl mx-auto space-y-6">
            <div className="bg-gradient-to-r from-indigo-600 to-purple-600 rounded-2xl p-8 text-white shadow-lg">
                <div className="flex items-start justify-between">
                    <div>
                        <h2 className="text-3xl font-bold flex items-center gap-3">
                            <Sparkles className="w-8 h-8 text-yellow-300" />
                            AI Attendance Analyst
                        </h2>
                        <p className="mt-2 text-indigo-100 max-w-xl">
                            Leverage Google Gemini 2.5 Flash to analyze attendance patterns, identify at-risk students, and generate actionable insights instantly.
                        </p>
                    </div>
                    <button
                        onClick={generateReport}
                        disabled={loading}
                        className="bg-white text-indigo-600 px-6 py-3 rounded-lg font-semibold shadow-md hover:bg-indigo-50 transition-colors flex items-center gap-2 disabled:opacity-70 disabled:cursor-not-allowed"
                    >
                        {loading ? <Loader2 className="w-5 h-5 animate-spin" /> : <FileText className="w-5 h-5" />}
                        {loading ? 'Analyzing Data...' : 'Generate Report'}
                    </button>
                </div>
            </div>

            {error && (
                <div className="bg-red-50 text-red-700 p-4 rounded-lg border border-red-200 flex items-center gap-3">
                    <AlertCircle className="w-5 h-5" />
                    {error}
                </div>
            )}

            {report && (
                <div className="bg-white rounded-xl shadow-sm border border-slate-100 p-8 animate-fade-in">
                    <div className="prose prose-slate max-w-none">
                        {/*
              Tailwind typography plugin usually handles 'prose', 
              but since we're using CDN, we might need basic styles or rely on standard tags. 
              The react-markdown will render standard HTML tags.
              We'll add some custom styling wrappers.
            */}
                        <ReactMarkdown
                            components={{
                                h1: ({node, ...props}) => <h1 className="text-2xl font-bold text-slate-900 mb-4" {...props} />,
                                h2: ({node, ...props}) => <h2 className="text-xl font-bold text-slate-800 mt-6 mb-3" {...props} />,
                                h3: ({node, ...props}) => <h3 className="text-lg font-semibold text-slate-800 mt-4 mb-2" {...props} />,
                                ul: ({node, ...props}) => <ul className="list-disc pl-5 space-y-2 text-slate-700 mb-4" {...props} />,
                                li: ({node, ...props}) => <li className="text-slate-700" {...props} />,
                                p: ({node, ...props}) => <p className="text-slate-600 mb-4 leading-relaxed" {...props} />,
                                strong: ({node, ...props}) => <strong className="font-semibold text-slate-900" {...props} />,
                            }}
                        >
                            {report}
                        </ReactMarkdown>
                    </div>

                    <div className="mt-8 pt-6 border-t border-slate-100 flex justify-between text-sm text-slate-400">
                        <span>Generated by Gemini 2.5 Flash</span>
                        <span>{new Date().toLocaleDateString()}</span>
                    </div>
                </div>
            )}

            {!report && !loading && (
                <div className="text-center py-12 bg-slate-50 rounded-xl border border-dashed border-slate-300">
                    <div className="mx-auto w-16 h-16 bg-slate-100 rounded-full flex items-center justify-center mb-4">
                        <Sparkles className="w-8 h-8 text-slate-400" />
                    </div>
                    <h3 className="text-lg font-medium text-slate-600">No Analysis Generated Yet</h3>
                    <p className="text-slate-400">Click the button above to analyze current attendance records.</p>
                </div>
            )}
        </div>
    );
};

export default GeminiInsights;